# Generated by Django 5.1.1 on 2024-12-16 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='video',
            name='uploaded_by',
        ),
    ]
